### PR TITLE
fix d2t relaying both redirection

### LINKED ISSUE #435: D2T relay issue: relays from both sides even if d2t is set.
```yaml
telegram:
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
  useCustomEmojiFilter: false
  replaceAtWithHash: false
  replaceExcessiveSpaces: false
  removeNewlineSpaces: false
  suppressFileTooBigMessages: false
  suppressThisIsPrivateBotMessage: false
  token: dum
discord:
  skipOldMessages: true
  useNickname: false
  replyLength: 100
  maxReplyLines: 2
  suppressThisIsPrivateBotMessage: false
  enableCustomStatus: false
  customStatusMessage: TediCross
  useEmbeds: auto
  token: dum
debug: false
messageTimeoutAmount: 24
messageTimeoutUnit: hours
persistentMessageMap: false
bridges:
  - name: First bridge
    direction: d2t
    telegram:
      chatId: -100219938865
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      crossDeleteOnDiscord: false
    discord:
      channelId: '126717621933021595'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      crossDeleteOnTelegram: false
      disableWebPreviewOnTelegram: false
      useEmbeds: auto
      ```
      
      Did reset bot token to see , same issue. both and t2d redirection work fine

### PR DESCRIPTION
**Pull request by bilal-the-dev**
Saw d2t was relaying both directions and apparently the params order were wrong causing objects to not be filtered from bridges.

### CODE REVIEW

File: src/telegram2discord/middlewares.ts [hunk 1]
```diff
@@ -219,7 +219,7 @@ function addBridgesToContext(ctx: TediCrossContext, next: () => void) {
  * @param next Function to pass control to next middleware
  */
 function removeD2TBridges(ctx: TediCrossContext, next: () => void) {
-	ctx.tediCross.bridges = R.reject(R.propEq("direction", Bridge.DIRECTION_DISCORD_TO_TELEGRAM))(
+	ctx.tediCross.bridges = R.reject(R.propEq( Bridge.DIRECTION_DISCORD_TO_TELEGRAM, "direction"))(
```
Comment (Lulalaby) [inline src/telegram2discord/middlewares.ts]:
```suggestion
	ctx.tediCross.bridges = R.reject(R.propEq(Bridge.DIRECTION_DISCORD_TO_TELEGRAM, "direction"))(
```

**Review by Lulalaby — COMMENTED** [review]
Thank you! I will publish the update in a while
